---
- name: Install Apache, Git, Java 17, Jenkins, Docker, and Kubernetes
  hosts: all
  become: true

  tasks:
    - name: Update system packages
      shell: yum update -y
      ignore_errors: yes

    - name: Remove broken old Kubernetes repo (if any)
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: absent

    - name: Add updated Kubernetes repo
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key

    - name: Install Apache HTTP Server
      shell: yum install -y httpd
      ignore_errors: yes

    - name: Start and enable Apache
      shell: |
        systemctl start httpd
        systemctl enable httpd

    - name: Install Git
      shell: yum install -y git
      ignore_errors: yes

    - name: Enable corretto17 (Amazon Linux 2)
      shell: amazon-linux-extras enable corretto17 || true
      ignore_errors: yes

    - name: Install Java 17 (Corretto)
      shell: yum install -y java-17-amazon-corretto
      ignore_errors: yes

    - name: Add Jenkins repo
      shell: |
        wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
        rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins
      shell: yum install -y jenkins
      ignore_errors: yes

    - name: Start and enable Jenkins
      shell: |
        systemctl daemon-reexec
        systemctl enable jenkins
        systemctl start jenkins

    - name: Install Docker
      shell: yum install -y docker
      ignore_errors: yes

    - name: Start and enable Docker
      shell: |
        systemctl daemon-reexec
        systemctl enable docker
        systemctl start docker

    - name: Install Kubernetes packages
      shell: |
        yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
        systemctl enable --now kubelet

    - name: Initialize Kubernetes cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Configure kubectl for ec2-user
      shell: |
        mkdir -p /home/ec2-user/.kube
        cp -i /etc/kubernetes/admin.conf /home/ec2-user/.kube/config
        chown ec2-user:ec2-user /home/ec2-user/.kube/config
      ignore_errors: yes

    - name: Allow master node to schedule pods
      shell: kubectl taint nodes --all node-role.kubernetes.io/master- || true
      ignore_errors: yes
    - name: Install Flannel CNI
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: flannel_apply
      retries: 5
      delay: 10
      until: flannel_apply.rc == 0

